# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-A7-100-Master.xdc

# IP: ip/axis_data_fifo_1/axis_data_fifo_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_1 || ORIG_REF_NAME==axis_data_fifo_1} -quiet] -quiet
